/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Logica.LogicClass;
import Abstratos.Registros;
import Logica.Principal;
import java.awt.Color;

/**
 *
 * @author pierr
 */
public class InterfaceCadastro extends javax.swing.JFrame {
    public InterfaceCadastro() {
        initComponents();
        setLocationRelativeTo( null );
        setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
        Color Cor = new Color(132, 20, 12);
        getContentPane().setBackground(Cor);
        //Titulo
        lblTitulo.setIcon(LogicClass.addImagem("src/Imagens/cadastro.png", lblTitulo));
        //Guina
        lblGuinaTeclando.setIcon(LogicClass.addImagem("src/Imagens/guina_teclando.png", lblGuinaTeclando));
        //Voltar
        lblVoltarTelaInicial1.setIcon(LogicClass.addImagem("src/Imagens/btn_voltar_menu_sem_borda.png", lblVoltarTelaInicial1));
        //Cadastrar
        lblCadastrarNovoUsuario.setIcon(LogicClass.addImagem("src/Imagens/btn_cadastrar_novo_sem_borda.png", lblCadastrarNovoUsuario));
        //Sair
        lblSair.setIcon(LogicClass.addImagem("src/Imagens/btn_sair_sem_borda.png", lblSair));
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblGuinaTeclando = new javax.swing.JLabel();
        lblInfos = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        txtLogin = new javax.swing.JTextField();
        txtCpf = new javax.swing.JFormattedTextField();
        txtContato = new javax.swing.JFormattedTextField();
        lblCadastrarNovoUsuario = new javax.swing.JLabel();
        lblSair = new javax.swing.JLabel();
        lblVoltarTelaInicial1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cadastro.png"))); // NOI18N
        lblTitulo.setText("jLabel1");

        lblGuinaTeclando.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/guina_teclando.png"))); // NOI18N
        lblGuinaTeclando.setText("jLabel1");

        lblInfos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/coisas_do_cadastro.jpg"))); // NOI18N
        lblInfos.setText("jLabel1");

        txtNome.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N

        txtSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSenhaMouseClicked(evt);
            }
        });

        txtLogin.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N

        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtContato.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblCadastrarNovoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/btn_cadastrar_novo_sem_borda.png"))); // NOI18N
        lblCadastrarNovoUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCadastrarNovoUsuarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCadastrarNovoUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCadastrarNovoUsuarioMouseExited(evt);
            }
        });

        lblSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/btn_voltar_menu_sem_borda.png"))); // NOI18N
        lblSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSairMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSairMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSairMouseExited(evt);
            }
        });

        lblVoltarTelaInicial1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/btn_voltar_menu_sem_borda.png"))); // NOI18N
        lblVoltarTelaInicial1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVoltarTelaInicial1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblVoltarTelaInicial1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblVoltarTelaInicial1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblInfos, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblVoltarTelaInicial1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtContato, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(lblSair, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(lblCadastrarNovoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblGuinaTeclando, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(lblInfos, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addComponent(lblVoltarTelaInicial1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(txtContato, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addComponent(lblSair, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblCadastrarNovoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(250, 250, 250)
                .addComponent(lblGuinaTeclando, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCadastrarNovoUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadastrarNovoUsuarioMouseEntered
        lblCadastrarNovoUsuario.setIcon(LogicClass.addImagem("src/Imagens/btn_cadastrar_novo_com_borda.png", lblCadastrarNovoUsuario));
    }//GEN-LAST:event_lblCadastrarNovoUsuarioMouseEntered

    private void lblCadastrarNovoUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadastrarNovoUsuarioMouseExited
        lblCadastrarNovoUsuario.setIcon(LogicClass.addImagem("src/Imagens/btn_cadastrar_novo_sem_borda.png", lblCadastrarNovoUsuario));
    }//GEN-LAST:event_lblCadastrarNovoUsuarioMouseExited

    private void lblVoltarTelaInicial1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVoltarTelaInicial1MouseEntered
        lblVoltarTelaInicial1.setIcon(LogicClass.addImagem("src/Imagens/btn_voltar_menu_com_borda.png", lblVoltarTelaInicial1));
    }//GEN-LAST:event_lblVoltarTelaInicial1MouseEntered

    private void lblVoltarTelaInicial1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVoltarTelaInicial1MouseExited
        lblVoltarTelaInicial1.setIcon(LogicClass.addImagem("src/Imagens/btn_voltar_menu_sem_borda.png", lblVoltarTelaInicial1));
    }//GEN-LAST:event_lblVoltarTelaInicial1MouseExited

    private void lblSairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSairMouseEntered
        lblSair.setIcon(LogicClass.addImagem("src/Imagens/btn_sair_com_borda.png", lblSair));
    }//GEN-LAST:event_lblSairMouseEntered

    private void lblSairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSairMouseExited
        lblSair.setIcon(LogicClass.addImagem("src/Imagens/btn_sair_sem_borda.png", lblSair));
    }//GEN-LAST:event_lblSairMouseExited

    private void lblSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSairMouseClicked
        Principal.audios.selecionarMusica("mouse");
        System.exit(0);
    }//GEN-LAST:event_lblSairMouseClicked

    private void lblCadastrarNovoUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadastrarNovoUsuarioMouseClicked
        Principal.audios.selecionarMusica("mouse");
        String nome = txtNome.getText();
        String cpf = txtCpf.getText();
        String contato = txtContato.getText();
        if(!txtLogin.getText().contains("@demacol.com")){
            txtLogin.setText(txtLogin.getText()+"@demacol.com");
        }
        String login = txtLogin.getText();
        String senha = String.valueOf(txtSenha.getPassword());
        Registros registro = new Registros("users");
        registro.CadastrarUsuario(nome, cpf, contato, login, senha);
    }//GEN-LAST:event_lblCadastrarNovoUsuarioMouseClicked

    private void lblVoltarTelaInicial1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVoltarTelaInicial1MouseClicked
        Principal.audios.selecionarMusica("mouse");
        this.dispose();
        Logica.Principal.main(null);
    }//GEN-LAST:event_lblVoltarTelaInicial1MouseClicked

    private void txtSenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSenhaMouseClicked
        txtLogin.setText(txtLogin.getText()+"@demacol.com");
    }//GEN-LAST:event_txtSenhaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblCadastrarNovoUsuario;
    private javax.swing.JLabel lblGuinaTeclando;
    private javax.swing.JLabel lblInfos;
    private javax.swing.JLabel lblSair;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblVoltarTelaInicial1;
    private javax.swing.JFormattedTextField txtContato;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtNome;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
