/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import static Logica.AbreTelas.exibeTelaLoginUsers;
import Logica.LogicClass;
import Logica.Principal;
import TrataErro.NaoExisteUsuario;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author pierr
 */
public class InterfaceLogin extends javax.swing.JFrame {
    public InterfaceLogin() {
        initComponents();
        setLocationRelativeTo( null );
        setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
        Color Cor = new Color(132, 20, 12);
        getContentPane().setBackground(Cor);
        //Voltar
        lblVoltarMenuPrincipal.setIcon(LogicClass.addImagem("src/Imagens/btn_voltar_menu_sem_borda.png", lblVoltarMenuPrincipal));
        //Jailson
        lblJailson.setIcon(LogicClass.addImagem("src/Imagens/jailson_login.png", lblJailson));
        //Sair
        lblSair.setIcon(LogicClass.addImagem("src/Imagens/btn_sair_sem_borda.png", lblSair));
        //Logar
        lblLogar.setIcon(LogicClass.addImagem("src/Imagens/btn_login_sem_borda.png", lblLogar));
        //Titulo
        lblTitulo.setIcon(LogicClass.addImagem("src/Imagens/login.png", lblTitulo));
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogin = new javax.swing.JLabel();
        lblJailson = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        txtNome = new javax.swing.JTextField();
        lblSair = new javax.swing.JLabel();
        lblVoltarMenuPrincipal = new javax.swing.JLabel();
        lblLogar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/coisas_do_login.jpg"))); // NOI18N

        lblJailson.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/jailson_login.png"))); // NOI18N
        lblJailson.setText("jLabel1");

        lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/login.png"))); // NOI18N
        lblTitulo.setText("jLabel1");

        jPasswordField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPasswordField1MouseEntered(evt);
            }
        });

        txtNome.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N

        lblSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/btn_voltar_menu_sem_borda.png"))); // NOI18N
        lblSair.setText("jLabel1");
        lblSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSairMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSairMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSairMouseExited(evt);
            }
        });

        lblVoltarMenuPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/btn_voltar_menu_sem_borda.png"))); // NOI18N
        lblVoltarMenuPrincipal.setText("jLabel1");
        lblVoltarMenuPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVoltarMenuPrincipalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblVoltarMenuPrincipalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblVoltarMenuPrincipalMouseExited(evt);
            }
        });

        lblLogar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/btn_voltar_menu_sem_borda.png"))); // NOI18N
        lblLogar.setText("jLabel1");
        lblLogar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLogarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLogarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(lblLogin)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63)
                        .addComponent(lblLogar, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblVoltarMenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSair, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(lblJailson, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblLogar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblJailson, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblSair, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblVoltarMenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblSairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSairMouseEntered
        lblSair.setIcon(LogicClass.addImagem("src/Imagens/btn_sair_com_borda.png", lblSair));
    }//GEN-LAST:event_lblSairMouseEntered

    private void lblSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSairMouseClicked
        Principal.audios.selecionarMusica("mouse");
        System.exit(0);
    }//GEN-LAST:event_lblSairMouseClicked

    private void lblSairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSairMouseExited
        lblSair.setIcon(LogicClass.addImagem("src/Imagens/btn_sair_sem_borda.png", lblSair));
    }//GEN-LAST:event_lblSairMouseExited

    private void lblLogarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogarMouseClicked
        Principal.audios.selecionarMusica("mouse");
        try {
            exibeTelaLoginUsers(this.txtNome.getText(), String.valueOf(jPasswordField1.getPassword()));
        } catch (NaoExisteUsuario ex) {
            Logger.getLogger(InterfaceLogin.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            this.dispose();
        }
    }//GEN-LAST:event_lblLogarMouseClicked

    private void lblLogarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogarMouseEntered
        lblLogar.setIcon(LogicClass.addImagem("src/Imagens/btn_login_com_borda.png", lblLogar));
    }//GEN-LAST:event_lblLogarMouseEntered

    private void lblLogarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogarMouseExited
        lblLogar.setIcon(LogicClass.addImagem("src/Imagens/btn_login_sem_borda.png", lblLogar));
    }//GEN-LAST:event_lblLogarMouseExited

    private void lblVoltarMenuPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVoltarMenuPrincipalMouseClicked
        Principal.audios.selecionarMusica("mouse");;
        this.dispose();
        Logica.Principal.main(null);
    }//GEN-LAST:event_lblVoltarMenuPrincipalMouseClicked

    private void lblVoltarMenuPrincipalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVoltarMenuPrincipalMouseEntered
        lblVoltarMenuPrincipal.setIcon(LogicClass.addImagem("src/Imagens/btn_voltar_menu_com_borda.png", lblVoltarMenuPrincipal));
    }//GEN-LAST:event_lblVoltarMenuPrincipalMouseEntered

    private void lblVoltarMenuPrincipalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVoltarMenuPrincipalMouseExited
        lblVoltarMenuPrincipal.setIcon(LogicClass.addImagem("src/Imagens/btn_voltar_menu_sem_borda.png", lblVoltarMenuPrincipal));
    }//GEN-LAST:event_lblVoltarMenuPrincipalMouseExited

    private void jPasswordField1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField1MouseEntered

        if(!LogicClass.verificaDemacol(this.txtNome.getText())){
            this.txtNome.setText(this.txtNome.getText()+"@demacol.com");
        }
    }//GEN-LAST:event_jPasswordField1MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel lblJailson;
    private javax.swing.JLabel lblLogar;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblSair;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblVoltarMenuPrincipal;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
