package Interface;

import static Logica.AbreTelas.abreCadastro;
import static Logica.AbreTelas.abreCreditos;
import static Logica.AbreTelas.abreLogin;
import Logica.LogicClass;
import Logica.Principal;
import java.awt.Color;

/**
 *
 * @author aluno
 */
public class InterfaceFarmacia extends javax.swing.JFrame {
    /**
     * Creates new form InterfaceFarmacia
     */
    public InterfaceFarmacia() {
        initComponents();
        Color Cor = new Color(205, 101, 176);
        getContentPane().setBackground(Cor);
        setLocationRelativeTo( null );
        setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
        Principal.audios.selecionarMusica("soundJailson");
        //Colocando as imagens iniciais nos botoes
        //Cadastrar
        lblCadastrar.setIcon(LogicClass.addImagem("src/Imagens/btn_cadastrar_sem_borda.png", lblCadastrar));
        //Creditos
        lblCreditos.setIcon(LogicClass.addImagem("src/Imagens/btn_creditos_sem_borda.png", lblCreditos));
        //Login
        lblLogin.setIcon(LogicClass.addImagem("src/Imagens/btn_login_sem_borda.png", lblLogin));
        //Sair
        lblSair.setIcon(LogicClass.addImagem("src/Imagens/btn_sair_sem_borda.png", lblSair));
        //Titulo
        lblNomeFarmacia.setIcon(LogicClass.addImagem("src/Imagens/farmacia_do_guina.png", lblNomeFarmacia));
        //Guina falante
        lblGuinaFalando.setIcon(LogicClass.addImagem("src/Imagens/guina_fundo_rosa1.jpg", lblGuinaFalando));
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFaxada = new javax.swing.JLabel();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jScrollBar1 = new javax.swing.JScrollBar();
        lblNomeFarmacia = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();
        lblCreditos = new javax.swing.JLabel();
        lblCadastrar = new javax.swing.JLabel();
        lblGuinaFalando = new javax.swing.JLabel();
        lblSair = new javax.swing.JLabel();

        lblFaxada.setText("Faxada");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Farmácia do Guina");
        setBackground(new java.awt.Color(205, 101, 176));
        setResizable(false);

        lblNomeFarmacia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/farmacia_do_guina.png"))); // NOI18N
        lblNomeFarmacia.setText("jLabel2");

        lblLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/btn_login_sem_borda.png"))); // NOI18N
        lblLogin.setText("jLabel1");
        lblLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLoginMouseExited(evt);
            }
        });

        lblCreditos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/btn_creditos_sem_borda.png"))); // NOI18N
        lblCreditos.setText("jLabel1");
        lblCreditos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCreditosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCreditosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCreditosMouseExited(evt);
            }
        });

        lblCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/btn_cadastrar_sem_borda.png"))); // NOI18N
        lblCadastrar.setText("jLabel1");
        lblCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCadastrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCadastrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCadastrarMouseExited(evt);
            }
        });

        lblGuinaFalando.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/guina_fundo_rosa1.jpg"))); // NOI18N
        lblGuinaFalando.setText("jLabel1");

        lblSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/btn_sair_sem_borda.png"))); // NOI18N
        lblSair.setText("jLabel1");
        lblSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSairMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSairMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSairMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(147, Short.MAX_VALUE)
                .addComponent(lblNomeFarmacia, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(179, 179, 179))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(lblCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(lblLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(lblGuinaFalando, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(623, Short.MAX_VALUE)
                    .addComponent(lblSair, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(51, 51, 51)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblNomeFarmacia, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblGuinaFalando, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(112, 112, 112)
                    .addComponent(lblSair, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(322, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCadastrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadastrarMouseEntered
        lblCadastrar.setIcon(LogicClass.addImagem("src/Imagens/btn_cadastrar_com_borda.png", lblCadastrar));
    }//GEN-LAST:event_lblCadastrarMouseEntered

    private void lblCadastrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadastrarMouseExited
        lblCadastrar.setIcon(LogicClass.addImagem("src/Imagens/btn_cadastrar_sem_borda.png", lblCadastrar));
    }//GEN-LAST:event_lblCadastrarMouseExited

    private void lblLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginMouseEntered
       lblLogin.setIcon(LogicClass.addImagem("src/Imagens/btn_login_com_borda.png", lblLogin));
    }//GEN-LAST:event_lblLoginMouseEntered

    private void lblLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginMouseExited
        lblLogin.setIcon(LogicClass.addImagem("src/Imagens/btn_login_sem_borda.png", lblLogin));
    }//GEN-LAST:event_lblLoginMouseExited

    private void lblSairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSairMouseEntered
        lblSair.setIcon(LogicClass.addImagem("src/Imagens/btn_sair_com_borda.png", lblSair));
    }//GEN-LAST:event_lblSairMouseEntered

    private void lblSairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSairMouseExited
        lblSair.setIcon(LogicClass.addImagem("src/Imagens/btn_sair_sem_borda.png", lblSair));
    }//GEN-LAST:event_lblSairMouseExited

    private void lblCreditosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCreditosMouseEntered
        lblCreditos.setIcon(LogicClass.addImagem("src/Imagens/btn_creditos_com_borda.png", lblCreditos));
    }//GEN-LAST:event_lblCreditosMouseEntered

    private void lblCreditosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCreditosMouseExited
        lblCreditos.setIcon(LogicClass.addImagem("src/Imagens/btn_creditos_sem_borda.png", lblCreditos));
    }//GEN-LAST:event_lblCreditosMouseExited

    private void lblSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSairMouseClicked
        Principal.audios.selecionarMusica("mouse");
        System.exit(0);
    }//GEN-LAST:event_lblSairMouseClicked

    private void lblLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginMouseClicked
        Principal.audios.selecionarMusica("mouse");
        this.dispose();
        abreLogin();
    }//GEN-LAST:event_lblLoginMouseClicked

    private void lblCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadastrarMouseClicked
        Principal.audios.selecionarMusica("mouse");
        this.dispose();
        abreCadastro();
    }//GEN-LAST:event_lblCadastrarMouseClicked

    private void lblCreditosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCreditosMouseClicked
        Principal.audios.selecionarMusica("mouse");
        this.dispose();
        abreCreditos();
    }//GEN-LAST:event_lblCreditosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceFarmacia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceFarmacia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceFarmacia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceFarmacia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceFarmacia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JLabel lblCadastrar;
    private javax.swing.JLabel lblCreditos;
    private javax.swing.JLabel lblFaxada;
    private javax.swing.JLabel lblGuinaFalando;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblNomeFarmacia;
    private javax.swing.JLabel lblSair;
    // End of variables declaration//GEN-END:variables
}
