/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Concretos.Jogador;
import static Logica.AbreTelas.abreTelaApostas;
import static Logica.Conversoes.formatar;
import Logica.LogicClass;
import static Logica.LogicaParaArquivos.salvarDadosJogador;
import Logica.Principal;
import java.awt.Color;

/**
 *
 * @author pierre
 */
public class InterfaceJogoDoBicho extends javax.swing.JFrame {
    /**
     * Creates new form InterfaceJogoDoBicho
     * @param playerJogador = quem está jogando o jogo do bicho no momento.
     * Os botões estão propositalmente com a porcentagem errada (é jogo do bicho men kkkk)
     */
    private float saldo_jogador;
    private String dificuldade = "";
    private Jogador playerJogador;
    private float valor_aposta;
    public InterfaceJogoDoBicho(Jogador playerJogador) {
        initComponents();
        Principal.audios.selecionarMusica("soundPinkFloyd");
        setLocationRelativeTo( null );
        setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
        this.playerJogador = playerJogador;
        this.valor_aposta = 0;
        Color Cor = new Color(255, 255, 0);
        getContentPane().setBackground(Cor);
        lblFazerAposta.setIcon(LogicClass.addImagem("src/Imagens/btn_escolher_sem_borda.png", lblFazerAposta));
        lblVoltarMenuPrincipal.setIcon(LogicClass.addImagem("src/Imagens/btn_sair_sem_borda.png", lblVoltarMenuPrincipal));
        lblFacil.setIcon(LogicClass.addImagem("src/Imagens/btnFacil_sem_borda.png", lblFacil));
        lblMedio.setIcon(LogicClass.addImagem("src/Imagens/btnMedio_sem_borda.png", lblMedio));
        lblDificil.setIcon(LogicClass.addImagem("src/Imagens/btnDificil_sem_borda.png", lblDificil));
        lblFodas1.setIcon(LogicClass.addImagem("src/Imagens/btnFodas_sem_borda.png", lblFodas1));
        lblJailson.setIcon(LogicClass.addImagem("src/Imagens/jailson_terno_poker.png", lblJailson));
        lblTitulo.setIcon(LogicClass.addImagem("src/Imagens/jogo_do_bicho_titulo.jpg", lblTitulo));
        txtSaldo.setText(txtSaldo.getText()+" "+Float.toString(playerJogador.getSaldo()));
        txtSaldo.setEditable(false);
        this.saldo_jogador = playerJogador.getSaldo();
        this.valor_aposta = (float) (0.01*playerJogador.getSaldo());
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFacil = new javax.swing.JLabel();
        lblFazerAposta = new javax.swing.JLabel();
        lblVoltarMenuPrincipal = new javax.swing.JLabel();
        lblMedio = new javax.swing.JLabel();
        lblJailson = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblDificil = new javax.swing.JLabel();
        spinnerPorcentagem = new javax.swing.JSpinner();
        txtSaldo = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        lblFodas1 = new javax.swing.JLabel();
        txtDoSeuValor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblFacil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/btnFacil_sem_borda.png"))); // NOI18N
        lblFacil.setText("jLabel1");
        lblFacil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFacilMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblFacilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblFacilMouseExited(evt);
            }
        });

        lblFazerAposta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/btn_escolher_sem_borda.png"))); // NOI18N
        lblFazerAposta.setText("jLabel1");
        lblFazerAposta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFazerApostaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblFazerApostaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblFazerApostaMouseExited(evt);
            }
        });

        lblVoltarMenuPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/btn_sair_sem_borda.png"))); // NOI18N
        lblVoltarMenuPrincipal.setText("jLabel1");
        lblVoltarMenuPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVoltarMenuPrincipalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblVoltarMenuPrincipalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblVoltarMenuPrincipalMouseExited(evt);
            }
        });

        lblMedio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/btnMedio_sem_borda.png"))); // NOI18N
        lblMedio.setText("jLabel1");
        lblMedio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMedioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMedioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMedioMouseExited(evt);
            }
        });

        lblJailson.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/jailson_terno_poker.png"))); // NOI18N
        lblJailson.setText("jLabel1");

        lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/jogo_do_bicho_titulo.jpg"))); // NOI18N
        lblTitulo.setText("jLabel2");

        lblDificil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/btnDificil_sem_borda.png"))); // NOI18N
        lblDificil.setText("jLabel1");
        lblDificil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDificilMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblDificilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblDificilMouseExited(evt);
            }
        });

        spinnerPorcentagem.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        spinnerPorcentagem.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));
        spinnerPorcentagem.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        spinnerPorcentagem.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerPorcentagemStateChanged(evt);
            }
        });

        txtSaldo.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        txtSaldo.setText("Saldo: R$");

        jTextField2.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        jTextField2.setText("    Apostar");

        lblFodas1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/btnFodas_sem_borda.png"))); // NOI18N
        lblFodas1.setText("jLabel1");
        lblFodas1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFodas1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblFodas1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblFodas1MouseExited(evt);
            }
        });

        txtDoSeuValor.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        txtDoSeuValor.setText("   % do seu valor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblVoltarMenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblJailson, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102)
                        .addComponent(lblFazerAposta, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(spinnerPorcentagem, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDoSeuValor, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFacil, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMedio, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDificil, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFodas1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVoltarMenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(spinnerPorcentagem, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDoSeuValor, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(lblJailson, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblFazerAposta, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(lblFacil, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(lblMedio, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(lblDificil, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(lblFodas1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblFacilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFacilMouseClicked
        Principal.audios.selecionarMusica("mouse");
        lblFacil.setIcon(LogicClass.addImagem("src/Imagens/btnFacil_com_borda_cinza.png", lblFacil));
        this.dificuldade = "facil";
        lblMedio.setIcon(LogicClass.addImagem("src/Imagens/btnMedio_sem_borda.png", lblMedio));
        lblDificil.setIcon(LogicClass.addImagem("src/Imagens/btnDificil_sem_borda.png", lblDificil));
        lblFodas1.setIcon(LogicClass.addImagem("src/Imagens/btnFodas_sem_borda.png", lblFodas1));
    }//GEN-LAST:event_lblFacilMouseClicked

    private void lblFacilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFacilMouseEntered
        if(!this.dificuldade.equals("facil")){
            lblFacil.setIcon(LogicClass.addImagem("src/Imagens/btnFacil_com_borda.png", lblFacil));
        }
        else{
            lblFacil.setIcon(LogicClass.addImagem("src/Imagens/btnFacil_com_borda_cinza.png", lblFacil));
        }
    }//GEN-LAST:event_lblFacilMouseEntered

    private void lblFacilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFacilMouseExited
        if(!this.dificuldade.equals("facil")){
            lblFacil.setIcon(LogicClass.addImagem("src/Imagens/btnFacil_sem_borda.png", lblFacil));
        }
        else{
            lblFacil.setIcon(LogicClass.addImagem("src/Imagens/btnFacil_sem_borda_cinza.png", lblFacil));
        }
    }//GEN-LAST:event_lblFacilMouseExited

    private void lblFazerApostaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFazerApostaMouseClicked
        Principal.audios.selecionarMusica("mouse");
        if(!this.dificuldade.equals("")){
            abreTelaApostas(playerJogador, this.dificuldade, this.valor_aposta);
            this.dispose();
        }
    }//GEN-LAST:event_lblFazerApostaMouseClicked

    private void lblFazerApostaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFazerApostaMouseEntered
        lblFazerAposta.setIcon(LogicClass.addImagem("src/Imagens/btn_escolher_com_borda.png", lblFazerAposta));
    }//GEN-LAST:event_lblFazerApostaMouseEntered

    private void lblFazerApostaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFazerApostaMouseExited
        lblFazerAposta.setIcon(LogicClass.addImagem("src/Imagens/btn_escolher_sem_borda.png", lblFazerAposta));
    }//GEN-LAST:event_lblFazerApostaMouseExited

    private void lblVoltarMenuPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVoltarMenuPrincipalMouseClicked
        Principal.audios.selecionarMusica("mouse");
        salvarDadosJogador(this.playerJogador);
        System.exit(0);
    }//GEN-LAST:event_lblVoltarMenuPrincipalMouseClicked

    private void lblVoltarMenuPrincipalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVoltarMenuPrincipalMouseEntered
        lblVoltarMenuPrincipal.setIcon(LogicClass.addImagem("src/Imagens/btn_sair_com_borda.png", lblVoltarMenuPrincipal));
    }//GEN-LAST:event_lblVoltarMenuPrincipalMouseEntered

    private void lblVoltarMenuPrincipalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVoltarMenuPrincipalMouseExited
        lblVoltarMenuPrincipal.setIcon(LogicClass.addImagem("src/Imagens/btn_sair_sem_borda.png", lblVoltarMenuPrincipal));
    }//GEN-LAST:event_lblVoltarMenuPrincipalMouseExited

    private void lblMedioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMedioMouseClicked
        Principal.audios.selecionarMusica("mouse");
        this.dificuldade = "medio";
        lblMedio.setIcon(LogicClass.addImagem("src/Imagens/btnMedio_com_borda_cinza.png", lblMedio));
        lblFacil.setIcon(LogicClass.addImagem("src/Imagens/btnFacil_sem_borda.png", lblFacil));
        lblDificil.setIcon(LogicClass.addImagem("src/Imagens/btnDificil_sem_borda.png", lblDificil));
        lblFodas1.setIcon(LogicClass.addImagem("src/Imagens/btnFodas_sem_borda.png", lblFodas1));
    }//GEN-LAST:event_lblMedioMouseClicked

    private void lblMedioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMedioMouseEntered
        if(!this.dificuldade.equals("medio")){
            lblMedio.setIcon(LogicClass.addImagem("src/Imagens/btnMedio_com_borda.png", lblMedio));
        }
        else{
            lblMedio.setIcon(LogicClass.addImagem("src/Imagens/btnMedio_com_borda_cinza.png", lblMedio));
        }
        
    }//GEN-LAST:event_lblMedioMouseEntered

    private void lblMedioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMedioMouseExited
        if(!this.dificuldade.equals("medio")){
            lblMedio.setIcon(LogicClass.addImagem("src/Imagens/btnMedio_sem_borda.png", lblMedio));
        }
        else{
            lblMedio.setIcon(LogicClass.addImagem("src/Imagens/btnMedio_sem_borda_cinza.png", lblMedio));
        }
    }//GEN-LAST:event_lblMedioMouseExited

    private void lblDificilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDificilMouseClicked
        Principal.audios.selecionarMusica("mouse");
        this.dificuldade = "dificil";
        lblDificil.setIcon(LogicClass.addImagem("src/Imagens/btnDificil_com_borda_cinza.png", lblDificil));
        lblFacil.setIcon(LogicClass.addImagem("src/Imagens/btnFacil_sem_borda.png", lblFacil));
        lblMedio.setIcon(LogicClass.addImagem("src/Imagens/btnMedio_sem_borda.png", lblMedio));
        lblFodas1.setIcon(LogicClass.addImagem("src/Imagens/btnFodas_sem_borda.png", lblFodas1));
    }//GEN-LAST:event_lblDificilMouseClicked

    private void lblDificilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDificilMouseEntered
        if(!this.dificuldade.equals("dificil")){
            lblDificil.setIcon(LogicClass.addImagem("src/Imagens/btnDificil_com_borda.png", lblDificil));
        }
        else{
            lblDificil.setIcon(LogicClass.addImagem("src/Imagens/btnDificil_com_borda_cinza.png", lblDificil));
        }
    }//GEN-LAST:event_lblDificilMouseEntered

    private void lblDificilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDificilMouseExited
        if(!this.dificuldade.equals("dificil")){
            lblDificil.setIcon(LogicClass.addImagem("src/Imagens/btnDificil_sem_borda.png", lblDificil));
        }
        else{
            lblDificil.setIcon(LogicClass.addImagem("src/Imagens/btnDificil_sem_borda_cinza.png", lblDificil));
        }
    }//GEN-LAST:event_lblDificilMouseExited

    private void lblFodas1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFodas1MouseClicked
        Principal.audios.selecionarMusica("mouse");
        lblFodas1.setIcon(LogicClass.addImagem("src/Imagens/btnFodas_com_borda_cinza.png", lblFodas1));
        lblFacil.setIcon(LogicClass.addImagem("src/Imagens/btnFacil_sem_borda.png", lblFacil));
        lblMedio.setIcon(LogicClass.addImagem("src/Imagens/btnMedio_sem_borda.png", lblMedio));
        lblDificil.setIcon(LogicClass.addImagem("src/Imagens/btnDificil_sem_borda.png", lblDificil));
        this.dificuldade = "fodas";
    }//GEN-LAST:event_lblFodas1MouseClicked

    private void lblFodas1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFodas1MouseEntered
        if(!this.dificuldade.equals("fodas")){
            lblFodas1.setIcon(LogicClass.addImagem("src/Imagens/btnFodas_com_borda.png", lblFodas1));
        }
        else{
            lblFodas1.setIcon(LogicClass.addImagem("src/Imagens/btnFodas_com_borda_cinza.png", lblFodas1));
        }
    }//GEN-LAST:event_lblFodas1MouseEntered

    private void lblFodas1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFodas1MouseExited
        if(!this.dificuldade.equals("fodas")){
            lblFodas1.setIcon(LogicClass.addImagem("src/Imagens/btnFodas_sem_borda.png", lblFodas1));
        }
        else{
            lblFodas1.setIcon(LogicClass.addImagem("src/Imagens/btnFodas_sem_borda_cinza.png", lblFodas1));
        }
    }//GEN-LAST:event_lblFodas1MouseExited

    private void spinnerPorcentagemStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerPorcentagemStateChanged
        float num = Float.parseFloat(spinnerPorcentagem.getValue().toString());
        String string;
        this.valor_aposta = (float) (num*0.01*this.saldo_jogador);
        string = formatar(Float.toString(this.valor_aposta));
        this.txtDoSeuValor.setText(" % do seu valor --> R$ "+string);
    }//GEN-LAST:event_spinnerPorcentagemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceJogoDoBicho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceJogoDoBicho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceJogoDoBicho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceJogoDoBicho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceJogoDoBicho(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblDificil;
    private javax.swing.JLabel lblFacil;
    private javax.swing.JLabel lblFazerAposta;
    private javax.swing.JLabel lblFodas1;
    private javax.swing.JLabel lblJailson;
    private javax.swing.JLabel lblMedio;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblVoltarMenuPrincipal;
    private javax.swing.JSpinner spinnerPorcentagem;
    private javax.swing.JTextField txtDoSeuValor;
    private javax.swing.JTextField txtSaldo;
    // End of variables declaration//GEN-END:variables
}
