/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Concretos.Animal;
import Concretos.Jogador;
import static Logica.AbreTelas.abrirAposta;
import static Logica.Conversoes.formatar;
import Logica.LogicClass;
import static Logica.LogicaParaArquivos.salvarDadosJogador;
import Logica.Principal;
import java.awt.Color;

/**
 *
 * @author pierr
 */
public class InterfaceResultado extends javax.swing.JFrame {
    
    private Jogador jogador;
    public InterfaceResultado(Jogador playerJogador, Animal resultado) {
        initComponents();
        setLocationRelativeTo( null );
        setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
        Color Cor = new Color(0, 0, 0);
        getContentPane().setBackground(Cor);
        jogador = playerJogador;
        lblApostarMais.setIcon(LogicClass.addImagem("src/Imagens/btn_novo_jogo_sem_borda.png", lblApostarMais));
        lblSair.setIcon(LogicClass.addImagem("src/Imagens/btn_sair_sem_borda.png", lblSair));
        lblVoltar.setIcon(LogicClass.addImagem("src/Imagens/btn_voltar_menu_sem_borda.png", lblVoltar));
        this.lblSaldoDisponivel.setText("Saldo disponível: "+Float.toString(this.jogador.getSaldo()));
        //lblAguia.setIcon(LogicClass.addImagem("src/Imagens/aguia_sem_borda.png", lblAguia));
        if(resultado.isEscolhido()){
            lbl0.setIcon(LogicClass.addImagem("src/Imagens/"+resultado.getNome()+"_com_borda.png", lbl0));
            lblGuinaOutro.setIcon(LogicClass.addImagem("src/Imagens/acerto_mizeravi.jpg", lblGuinaOutro));
            lblResultado.setIcon(LogicClass.addImagem("src/Imagens/ganhou.png", lblResultado));
            Principal.audios.selecionarMusica("acertou");
        }
        else{
            lbl0.setIcon(LogicClass.addImagem("src/Imagens/"+resultado.getNome()+"_sem_borda.png", lbl0));
            lblGuinaOutro.setIcon(LogicClass.addImagem("src/Imagens/guina_chorando_png.png", lblGuinaOutro));
            lblResultado.setIcon(LogicClass.addImagem("src/Imagens/perdeu.png", lblResultado));
            Principal.audios.selecionarMusica("errou");
        }
       lblResultadoBicho.setIcon(LogicClass.addImagem("src/Imagens/sorteado.png", lblResultadoBicho));
       this.lblSaldoDisponivel.setText("Saldo disponível: "+formatar(Float.toString(this.jogador.getSaldo())));
       setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl0 = new javax.swing.JLabel();
        lblSaldoDisponivel = new javax.swing.JLabel();
        lblSair = new javax.swing.JLabel();
        lblApostarMais = new javax.swing.JLabel();
        lblVoltar = new javax.swing.JLabel();
        lblResultado = new javax.swing.JLabel();
        lblResultadoBicho = new javax.swing.JLabel();
        lblGuinaOutro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/aguia_com_borda.png"))); // NOI18N
        lbl0.setText("jLabel1");

        lblSaldoDisponivel.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        lblSaldoDisponivel.setForeground(new java.awt.Color(255, 255, 255));
        lblSaldoDisponivel.setText("Saldo Disponível: R$ 00,00");

        lblSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/btn_sair_sem_borda.png"))); // NOI18N
        lblSair.setText("Sair");
        lblSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSairMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSairMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSairMouseExited(evt);
            }
        });

        lblApostarMais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/btn_sair_sem_borda.png"))); // NOI18N
        lblApostarMais.setText("Sair");
        lblApostarMais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblApostarMaisMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblApostarMaisMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblApostarMaisMouseExited(evt);
            }
        });

        lblVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/btn_sair_sem_borda.png"))); // NOI18N
        lblVoltar.setText("Sair");
        lblVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVoltarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblVoltarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblVoltarMouseExited(evt);
            }
        });

        lblResultado.setText("jLabel1");

        lblResultadoBicho.setText("jLabel2");

        lblGuinaOutro.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblSair, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(212, 212, 212)
                .addComponent(lblGuinaOutro, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(lblSaldoDisponivel, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblResultadoBicho, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(lbl0, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblApostarMais, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSaldoDisponivel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(lblResultadoBicho, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lbl0, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblApostarMais, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(lblVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(lblSair, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblGuinaOutro, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSairMouseClicked
        Principal.audios.selecionarMusica("mouse");
        salvarDadosJogador(this.jogador);
        System.exit(0);
    }//GEN-LAST:event_lblSairMouseClicked

    private void lblSairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSairMouseEntered
        lblSair.setIcon(LogicClass.addImagem("src/Imagens/btn_sair_com_borda.png", lblSair));
    }//GEN-LAST:event_lblSairMouseEntered

    private void lblSairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSairMouseExited
        lblSair.setIcon(LogicClass.addImagem("src/Imagens/btn_sair_sem_borda.png", lblSair));
    }//GEN-LAST:event_lblSairMouseExited

    private void lblApostarMaisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblApostarMaisMouseClicked
        Principal.audios.selecionarMusica("mouse");
        abrirAposta(this.jogador);
        this.dispose();
    }//GEN-LAST:event_lblApostarMaisMouseClicked

    private void lblApostarMaisMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblApostarMaisMouseEntered
        lblApostarMais.setIcon(LogicClass.addImagem("src/Imagens/btn_novo_jogo_com_borda.png", lblApostarMais));
    }//GEN-LAST:event_lblApostarMaisMouseEntered

    private void lblApostarMaisMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblApostarMaisMouseExited
      lblApostarMais.setIcon(LogicClass.addImagem("src/Imagens/btn_novo_jogo_sem_borda.png", lblApostarMais));
    }//GEN-LAST:event_lblApostarMaisMouseExited

    private void lblVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVoltarMouseClicked
        Principal.audios.selecionarMusica("mouse");
        salvarDadosJogador(this.jogador);
        Principal.main(null);
        this.dispose();
    }//GEN-LAST:event_lblVoltarMouseClicked

    private void lblVoltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVoltarMouseEntered
        lblVoltar.setIcon(LogicClass.addImagem("src/Imagens/btn_voltar_menu_com_borda.png", lblVoltar));
    }//GEN-LAST:event_lblVoltarMouseEntered

    private void lblVoltarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVoltarMouseExited
        lblVoltar.setIcon(LogicClass.addImagem("src/Imagens/btn_voltar_menu_sem_borda.png", lblVoltar));
    }//GEN-LAST:event_lblVoltarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceResultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceResultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceResultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceResultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceResultado(null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl0;
    private javax.swing.JLabel lblApostarMais;
    private javax.swing.JLabel lblGuinaOutro;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JLabel lblResultadoBicho;
    private javax.swing.JLabel lblSair;
    private javax.swing.JLabel lblSaldoDisponivel;
    private javax.swing.JLabel lblVoltar;
    // End of variables declaration//GEN-END:variables
}
